// Mocks generated by Mockito 5.4.6 from annotations
// in sos_mascotas/test/vista/reportes/video_recorte_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sos_mascotas/modelo/reporte_mascota.dart' as _i2;
import 'package:sos_mascotas/vistamodelo/reportes/reporte_vm.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReporteMascota_0 extends _i1.SmartFake
    implements _i2.ReporteMascota {
  _FakeReporteMascota_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReporteMascotaVM].
///
/// See the documentation for Mockito's code generation for more information.
class MockReporteMascotaVM extends _i1.Mock implements _i4.ReporteMascotaVM {
  @override
  _i2.ReporteMascota get reporte =>
      (super.noSuchMethod(
            Invocation.getter(#reporte),
            returnValue: _FakeReporteMascota_0(
              this,
              Invocation.getter(#reporte),
            ),
            returnValueForMissingStub: _FakeReporteMascota_0(
              this,
              Invocation.getter(#reporte),
            ),
          )
          as _i2.ReporteMascota);

  @override
  _i3.GlobalKey<_i3.FormState> get formKeyPaso1 =>
      (super.noSuchMethod(
            Invocation.getter(#formKeyPaso1),
            returnValue: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso1),
            ),
            returnValueForMissingStub: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso1),
            ),
          )
          as _i3.GlobalKey<_i3.FormState>);

  @override
  _i3.GlobalKey<_i3.FormState> get formKeyPaso2 =>
      (super.noSuchMethod(
            Invocation.getter(#formKeyPaso2),
            returnValue: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso2),
            ),
            returnValueForMissingStub: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso2),
            ),
          )
          as _i3.GlobalKey<_i3.FormState>);

  @override
  _i3.GlobalKey<_i3.FormState> get formKeyPaso3 =>
      (super.noSuchMethod(
            Invocation.getter(#formKeyPaso3),
            returnValue: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso3),
            ),
            returnValueForMissingStub: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKeyPaso3),
            ),
          )
          as _i3.GlobalKey<_i3.FormState>);

  @override
  int get paso =>
      (super.noSuchMethod(
            Invocation.getter(#paso),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get cargando =>
      (super.noSuchMethod(
            Invocation.getter(#cargando),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String> get fotos =>
      (super.noSuchMethod(
            Invocation.getter(#fotos),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get videos =>
      (super.noSuchMethod(
            Invocation.getter(#videos),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  set reporte(_i2.ReporteMascota? value) => super.noSuchMethod(
    Invocation.setter(#reporte, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setPaso(int? nuevoPaso) => super.noSuchMethod(
    Invocation.method(#setPaso, [nuevoPaso]),
    returnValueForMissingStub: null,
  );

  @override
  void siguientePaso() => super.noSuchMethod(
    Invocation.method(#siguientePaso, []),
    returnValueForMissingStub: null,
  );

  @override
  void pasoAnterior() => super.noSuchMethod(
    Invocation.method(#pasoAnterior, []),
    returnValueForMissingStub: null,
  );

  @override
  void agregarFoto(String? url) => super.noSuchMethod(
    Invocation.method(#agregarFoto, [url]),
    returnValueForMissingStub: null,
  );

  @override
  void agregarVideo(String? url) => super.noSuchMethod(
    Invocation.method(#agregarVideo, [url]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> subirFoto(_i6.File? archivo) =>
      (super.noSuchMethod(
            Invocation.method(#subirFoto, [archivo]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#subirFoto, [archivo]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#subirFoto, [archivo]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> subirVideo(_i6.File? archivo) =>
      (super.noSuchMethod(
            Invocation.method(#subirVideo, [archivo]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#subirVideo, [archivo]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#subirVideo, [archivo]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> guardarReporte() =>
      (super.noSuchMethod(
            Invocation.method(#guardarReporte, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
